### ISSUE TITLE
change location

### ISSUE THREAD

**Issue by 111YRY** [LukeWasTakenn/luke_garages#101]
Hello, can you please help me? Look, I made a new garage getting the coords from my ped and making a PolyZone with pzcreate box. The ped is inside de green box but won’t spawn. Any suggestions? I’m using trying this on a custom map. Thanks!

    {
        label = 'Paleto Bay Garage',
        type = 'car',
        pedCoords = vector4(82.4, 6421.93, 31.69, 43.79),
        zone = {name = 'paleto', x = 82.4, y = 6421.93, z = 31.69, l = 28.2, w = 52.2, h = 0, minZ = 40, maxZ = 40},
        spawns = {
            vector4(145.55, 6601.92, 31.67, 357.80),
            vector4(150.56, 6597.71, 31.67, 359.00),
            vector4(155.55, 6592.92, 31.67, 359.57),
            vector4(145.90, 6613.97, 31.64, 0.60),
            vector4(151.04, 6609.26, 31.69, 357.50),
            vector4(155.84, 6602.45, 31.86, 0.47),
        }
    },

**Comment by LukeWasTakenn** [comment]
It could be because your minZ and maxZ are same values.

Try increasing maxZ by 4.

**Comment by 111YRY** [comment]
The L W in the coordinates changes how to get it
