### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by TheZahamar** [LukeWasTakenn/luke_garages#102]
Hi, I have had a problem with cars on the server since the last time, the point is that the leds are added to the car randomly, or the car is standing but you cannot get in it stops the character or could it be a problem from garages? Such errors appear in the console from time to time

[    c-scripting-core] InvokeNative: execution failed: Tried to access invalid entity: 208211
[ script:luke_garages] SCRIPT ERROR: Execution of native 00000000e8522d58 in script host failed: Tried to access invalid entity: 208211
[ script:luke_garages] > <unknown> (@oxmysql/dist/build.js:21745)
[ script:luke_garages] > runMicrotasks (<anonymous>:0)
[ script:luke_garages] > processTicksAndRejections (node:internal/process/task_queues:96)
[ script:luke_garages] > async rawQuery (@oxmysql/dist/build.js:21735)

[    c-scripting-core] InvokeNative: execution failed: Tried to access invalid entity: 137504
[ script:luke_garages] SCRIPT ERROR: Execution of native 00000000e8522d58 in script host failed: Tried to access invalid entity: 137504

**Comment by LukeWasTakenn** [comment]
The vehicle properties are being applied by ox_lib so the LEDs thing is probably from that for whatever reason.

As for invalid entity I have no idea why that would be happening.

**Comment by TheZahamar** [comment]
There is also a problem on my server that when the car is pulled out of the garage, it is reborn outside the zone, e.g. on the street

**Comment by LukeWasTakenn** [comment]
> There is also a problem on my server that when the car is pulled out of the garage, it is reborn outside the zone, e.g. on the street

Probably an issue with one of your spawn points. I never encountered this.

**Comment by TheZahamar** [comment]
This problem occurs mainly with motorcycles, but with cars once in a while, I have been making parking spaces and entire garage zones from scratch and the problem still persists
