### ISSUE TITLE
Server sided issie

### ISSUE THREAD

**Issue by DazierModz** [LukeWasTakenn/luke_garages#104]
Hey,

Not sure If I'm just dumb, maybe I need sleep.

I'm trying to install your system and everytime I use the "3rd eye" and click on "take out vehicle" nothing happens. On the console, I get the errors below. 

I haven't changed your script at all. I just started it and updated the database.

[ script:luke_garages] SCRIPT ERROR: @luke_garages/server/server.lua:14: attempt to index a nil value (global 'ESX')
[ script:luke_garages] > cb (@luke_garages/server/server.lua:14)
[ script:luke_garages] > handler (@ox_lib/callback/server.lua:58)

EDIT* Would also like to add that nothing happens in the F8 console

**Comment by LukeWasTakenn** [comment]
> [ script:luke_garages] SCRIPT ERROR: @luke_garages/server/server.lua:14: attempt to index a nil value (global 'ESX')
[ script:luke_garages] > cb (@luke_garages/server/server.lua:14)
[ script:luke_garages] > handler (@ox_lib/callback/server.lua:58)

You're either starting ESX after starting my resource or you are not using ESX Legacy.
