### ISSUE TITLE
Cant name vehicles for custom car addons

### ISSUE THREAD

**Issue by cainrivera961** [LukeWasTakenn/luke_garages#111]
Its very hard to identify vehicles with custom cars added in because the NULL error, is there any way you can create a feature to rename the vehicles?
esx_advancedgarages had it and the sql column is name.

**Comment by LukeWasTakenn** [comment]
Please read the readme file.

**Comment by cainrivera961** [comment]
![image](https://user-images.githubusercontent.com/74611626/183302403-9b3c203f-a777-4b45-afa4-3cf0e4391c1c.png)
Hello, some vehicle names do not show up correctly even adding them in the vehicle lua file. and in the front it still says null also next to the ones that do work.

**Comment by cainrivera961** [comment]
also thank you for your fast reply

**Comment by LukeWasTakenn** [comment]
You need to edit the meta files for those vehicles to include manufacturer and game name. I don't know the name of the exact properties.

**Comment by cainrivera961** [comment]
I understand, we have way way to many vehicles for this. Maybe one day you will add vehicle names, if not thats understandable. Nice script regardless. Thanks for making free scripts. You Rock!

**Comment by Zzeyy** [comment]
> I understand, we have way way to many vehicles for this.

Then just make sure to set the names every time you add a new car.
