### ISSUE TITLE
OXMySQL

### ISSUE THREAD

**Issue by Alessandro0912** [LukeWasTakenn/luke_garages#115]
Please, make a Version for oxMySql because its now only for mysql-async!!!

**Comment by LukeWasTakenn** [comment]
oxmysql is backwards compatible with mysql-async therefore if you use oxmysql the queries are already going to be running through it.

**Comment by thelindat** [comment]
luke stop supporting mysql-async i need to increase my stonks
![image](https://user-images.githubusercontent.com/65407488/186694800-012eaf5d-64bf-428d-9a8b-a86b9e544213.png)
