### ISSUE TITLE
Fuel sometimes doesn't set properly?

### ISSUE THREAD

**Issue by katotekii** [LukeWasTakenn/luke_garages#116]
Has anybody else experienced that vehicle fuel sometimes doesn't set correctly?

Adding this

```lua
local fuel = json.decode(value.vehicle)
Entity(vehicle).state.fuel = tonumber(fuel.fuelLevel)
```
inside `vehicleData` state bag handler looks like helps

**Comment by LukeWasTakenn** [comment]
> Has anybody else experienced that vehicle fuel sometimes doesn't set correctly?

Would the value for fuel be 65 or something completely random?

**Comment by katotekii** [comment]
Totally randomly, above 65, under 65, currently using ox_fuel

**Comment by katotekii** [comment]
> Has anybody else experienced that vehicle fuel sometimes doesn't set correctly?
> 
> Adding this
> 
> ```lua
> local fuel = json.decode(value.vehicle)
> Entity(vehicle).state.fuel = tonumber(fuel.fuelLevel)
> ```
> 
> inside `vehicleData` state bag handler looks like helps

also with this sometimes it puts random level of fuel, it first sets correct one and in sec changes to something random, no other scripts interfer

**Comment by LukeWasTakenn** [comment]
ox_lib should be setting the vehicle fuel through the native, perhaps a weird sync issue with ox_fuel?

**Comment by katotekii** [comment]
Ik about lib setting it, just wanted to see does anybody else have this issue or just me

**Comment by Zzeyy** [comment]
Just you
