### ISSUE TITLE
airplanes boats and helicopters

### ISSUE THREAD

**Issue by eidertuning** [LukeWasTakenn/luke_garages#118]
It happens to me that when I try to store a plane or boat, etc., it saves them as a car type and not as a plane, so when I buy the vehicle it is not allowed to be stored in the corresponding garage, what is that due to, help me, thanks

**Comment by LukeWasTakenn** [comment]
This is an issue with the vehicle shop you are using which stores everything as a car type, it has nothing to do with my resource.
