### ISSUE TITLE
Car gets repaired (not the engine though)

### ISSUE THREAD

**Issue by Zzeyy** [LukeWasTakenn/luke_garages#122]
I've just tested out parking in and out a totaled car,
the body is always fine, but the engine stays the same, why is that?

**Comment by LukeWasTakenn** [comment]
Damage saving and applying is handled by ox_lib

**Comment by Zzeyy** [comment]
So there's no way for me or you to fix it, right?

**Comment by Zzeyy** [comment]
Damn... it worked just fine with the 1.5.0 release.
I wonder what went wrong while I wasn't hosting a fivem server.

**Comment by Zzeyy** [comment]
The windows do break too, it's just the body that is perfectly clean and untouched.
