### ISSUE TITLE
Issues with job garage

### ISSUE THREAD

**Issue by Zzeyy** [LukeWasTakenn/luke_garages#124]
```
    {
        label = 'MRPD Police Garage',
        type = 'car',
        job = {['police'] = 0},
        ped = `s_m_y_cop_01`,
        pedCoords = vector4(450.6633, -1027.3324, 27.5732, 5.1321),
        zone = {name = 'mrpd', x = 439.36, y= -1021.04, z = 28.83, l = 20, w = 40, h = 0, minZ = 27.03, maxZ = 31.03},
        spawns = {
            vector4(446.4181, -1026.2117, 28.2490, 357.9764),
            vector4(442.5637, -1025.5530, 28.2984, 1.7611),
            vector4(438.6664, -1027.0088, 28.3936, 3.1104),
            vector4(434.8707, -1026.6675, 28.4554, 3.9030),
            vector4(431.6170, -1026.7904, 28.5088, 0.9789),
            vector4(427.3045, -1027.6506, 28.5950, 5.8251)
        }
    },
```

![image](https://user-images.githubusercontent.com/97387354/194107225-5fe7af28-c731-49ef-95bb-8866c26ca063.png)

When restarting a server and then joining in and trying to view the garage this error pops up in the console.
![image](https://user-images.githubusercontent.com/97387354/194107396-2400f9f8-06cb-4c68-bf27-877c16bd9a75.png)

When changing my job from **police : 5** to **police : 0** it works fine but for one fact, there's no car in the garage.
So why does the error occur and why is there no car in the garage?

**Comment by Zzeyy** [comment]
I've just found this https://github.com/LukeWasTakenn/luke_garages/issues/103#issuecomment-1175948383
I'll restart the server and try everything again after setting the job value

**Comment by Zzeyy** [comment]
So the car now does appear in the garage as expected,
but the viewing errors are somewhat annoying and game breaking.

**Comment by LukeWasTakenn** [comment]
what version of ESX are you using?

**Comment by Zzeyy** [comment]
Es_Extended
```
{
	"version": "legacy",
	"commit" : "1.4.2",
	"changelog": "\n- Updated `Car` Command. Fixed some vulnerabilities. Fix SQL. Updated Commands."
}

```

**Comment by Zzeyy** [comment]
The one that has not received an update for almost 4 years, yeah, I know, I know.

**Comment by Zzeyy** [comment]
I can already see the problem is on my side. Perhaps you could suggest where to look?

**Comment by LukeWasTakenn** [comment]
You can try updating your ESX, not really sure 🤷

**Comment by Zzeyy** [comment]
How can I update something that's not been updated for four years? Can you send me a link for a newer version?

**Comment by LukeWasTakenn** [comment]
https://github.com/esx-framework/esx-legacy

**Comment by Zzeyy** [comment]
Thank you.
I could find this repository, just the other one.
I will let you know in a few hours if updating fixed the issue.

**Comment by Zzeyy** [comment]
Okay, it's been fixed. The car getting repaired after parking it has not been fixed though.
Oh, by the way, an option to hide a blip from a garage would be top.

**Comment by LukeWasTakenn** [comment]
> The car getting repaired after parking it has not been fixed though.

ox_lib handles saving vehicle damage so you'd have to see what's wrong there

**Comment by Zzeyy** [comment]
Unfortunately I did not edit ox_lib at all. So it's not my fault. Probably the default settings are at fault.

**Comment by Zzeyy** [comment]
![image](https://user-images.githubusercontent.com/97387354/195068646-f906211b-562e-44b9-bacf-07008b41bb55.png)

For whatever reason I'm getting too much offers right here.
And job garages don't appear on the map (though they do work).

**Comment by Zzeyy** [comment]
![image](https://user-images.githubusercontent.com/97387354/195069583-6d5d645e-ce44-4dd6-b1dc-8304ae96064c.png)

A second job garage.

**Comment by LukeWasTakenn** [comment]
hmm can I see how you defined the garage?

**Comment by Zzeyy** [comment]
Sure, here..

Config.Garages = {
    {
        label = 'Legion Garage',
        type = 'car', -- car, boat or aircraft
        pedCoords = vector4(215.90, -808.87, 29.74, 248.0), -- The Ped MUST be inside the PolyZone
        zone = {name = 'legion', x = 228.68, y = -789.15, z = 30.59, l = 52.4, w = 39.6, h = 340, minZ = 28.99, maxZ = 32.99},
        spawns = {
            vector4(206.25, -801.21, 31.00, 250.47),
            vector4(206.25, -801.21, 31.00, 250.47),
            vector4(208.72, -796.45, 30.95, 246.74),
            vector4(210.89, -791.42, 30.90, 248.02),
            vector4(216.12, -801.68, 30.80, 68.72),
            vector4(218.21, -796.79, 30.77, 68.80),
            vector4(219.76, -791.47, 30.76, 69.89),
            vector4(221.37, -786.53, 30.78, 70.72),
            vector4(212.52, -783.46, 30.89, 248.63),
        }
    },
    {
        label = 'Americano Way Garage',
        type = 'car',
        pedCoords = vector4(-1651.83, 63.90, 61.86, 338.03),
        zone = {name = 'americano', x = -1682.74, y = 60.93, z = 63.5, l = 59.6, w = 60.6, h = 329, minZ = 61.15, maxZ = 68.35},
        spawns = {
            vector4(-1660.57, 75.52, 63.20, 170.90),
            vector4(-1666.24, 79.84, 63.45, 171.92),
            vector4(-1671.97, 84.59, 63.83, 169.94),
            vector4(-1662.57, 57.99, 62.90, 293.91),
            vector4(-1664.75, 60.63, 63.05, 292.60),
            vector4(-1667.53, 62.90, 63.21, 291.82),
        }
    },
    {
        label = 'Route 68 Garage',
        type = 'car',
        pedCoords = vector4(587.23, 2723.50, 41.13, 7.85),
        zone = {name = 'route68', x = 573.19, y = 2727.17, z = 42.06, l = 22.4, w = 51.2, h = 4, minZ = 41.08, maxZ = 45.08},
        spawns = {
            vector4(584.51, 2721.56, 41.88, 3.59),
            vector4(581.14, 2721.32, 41.88, 3.99),
            vector4(578.15, 2720.59, 41.88, 4.65),
            vector4(574.86, 2721.09, 41.88, 4.85),
            vector4(572.01, 2720.28, 41.88, 5.40),
            vector4(568.78, 2720.25, 41.88, 5.15),
            vector4(565.86, 2719.79, 41.88, 3.42),
            vector4(562.68, 2719.95, 41.88, 3.98),
            vector4(559.54, 2719.52, 41.88, 3.45),
        }
    },
    {
        label = 'Paleto Bay Garage',
        type = 'car',
        pedCoords = vector4(140.62, 6613.02, 31.06, 183.37),
        zone = {name = 'paleto', x = 152.63, y = 6600.21, z = 30.84, l = 28.2, w = 27.2, h = 0, minZ = 30.84, maxZ = 34.84},
        spawns = {
            vector4(145.55, 6601.92, 31.67, 357.80),
            vector4(150.56, 6597.71, 31.67, 359.00),
            vector4(155.55, 6592.92, 31.67, 359.57),
            vector4(145.90, 6613.97, 31.64, 0.60),
            vector4(151.04, 6609.26, 31.69, 357.50),
            vector4(155.84, 6602.45, 31.86, 0.47),
        }
    },
    {
        label = 'Highway Pier Garage',
        type = 'boat',
        pedCoords = vector4(-3428.27, 967.34, 7.35, 269.47),
        zone = {name = 'pier', x = -3426.48, y =  968.89, z = 8.35, l = 31.2, w = 39.2, h = 0, minZ = nil, maxZ = nil},
        spawns = {
            vector4(-3444.37, 952.64, 1.02, 98.70),
            vector4(-3441.02, 965.30, 0.17, 87.18),
        }
    },
    {
        label = 'LSIA Garage',
        type = 'aircraft',
        pedCoords = vector4(-941.43, -2954.87, 12.95, 151.00),
        zone = {name = 'lsia', x = -968.31, y = -2992.47, z = 13.95, l = 94.4, w = 84.6, h = 330, minZ = nil, maxZ = nil},
        spawns = {
            vec4(-959.802185, -2982.342773, 13.929688, 59.527554),
            vec4(-975.415405, -2988.659424, 13.929688, 65.196854)
        }
    },
    {
        label = 'LSPD Garage',
        type = 'car',
        job = {['lspd'] = 0},
        ped = `s_m_y_cop_01`,
        pedCoords = vector4(450.6633, -1027.3324, 27.5732, 5.1321),
        zone = {name = 'mrpd', x = 439.36, y = -1021.04, z = 28.83, l = 20, w = 40, h = 0, minZ = 27.03, maxZ = 31.03},
        spawns = {
            vector4(446.4181, -1026.2117, 28.2490, 357.9764),
            vector4(442.5637, -1025.5530, 28.2984, 1.7611),
            vector4(438.6664, -1027.0088, 28.3936, 3.1104),
            vector4(434.8707, -1026.6675, 28.4554, 3.9030),
            vector4(431.6170, -1026.7904, 28.5088, 0.9789),
            vector4(427.3045, -1027.6506, 28.5950, 5.8251)
        }
    },
    {
        label = 'LSMC Garage',
        type = 'car',
        job = {['lsmc'] = 0},
        ped = `s_m_m_doctor_01`,
        pedCoords = vector4(319.3737, -559.4569, 27.7438, 21.0252),
        zone = {name = 'pillbox', x = 325.59, y = -549.27, z = 28.74, l = 25, w = 25, h = 0, minZ = 27.74, maxZ = 30.74},
        spawns = {
            vector4(321.0445, 542.4713, 28.5142, 180.9354),
            vector4(323.8813, 542.8687, 28.5135, 181.6986),
            vector4(326.6019, 542.6691, 28.5133, 179.8377),
            vector4(329.3755, 542.5102, 28.5137, 179.7974),
            vector4(332.2085, 542.5237, 28.5125, 181.5656)
        }
    },
--[[
    {
            label = 'Police Department Garage', -- name that will be displayed in menus
            type = 'car', -- can be 'car', 'boat' or 'aircraft',
            job = 'police', -- Set garage to be only accessed and stored into by a job (Optional)
            ped = `s_m_m_prisguard_01`, -- Define the model model you want to use for the garage (Optional)
            pedCoords = vector4(488.2596, -1024.0520, 27.0909, 99.5744), -- Ped MUST be inside the create zone
            zone = {name = 'pdg', x = 478.52, y = -1021.69, z = 28.01, l = 10, w = 25, h = 0, minZ = nil, maxZ = nil}, -- l is length of the box zone, w is width, h is heading, take all walues from generated zone from /pzcreate
            blip = { -- Define specific blip setting for this garage (Optional)
                scale = 0.8,
                sprite = 357,
                colour = 3
            },
            spawns = { -- You can have as many as you'd like
                vector4(482.3469, -1023.2355, 27.5723, 184.7763),
                vector4(479.0740, -1023.5912, 27.6284, 185.5990),
		vector4(475.7164, -1024.0094, 27.6964, 185.1897),
		vector4(472.2850, -1024.3579, 27.7638, 184.2591)
            }
        },
]]
    	{
            label = 'Strawberry Garage',
            type = 'car',
            pedCoords = vector4(148.8014, -1342.6536, 28.2023, 61.4284),
            zone = {name = 'Strawberry', x = 142.08, y = -1330.74, z = 28.49, l = 25, w = 25, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(151.2654, -1328.8422, 28.7030, 325.2524),
		vector4(148.8972, -1327.5149, 28.7006, 326.5832),
		vector4(145.6958, -1325.5587, 28.6985, 325.9776),
		vector4(143.0256, -1322.8969, 28.6998, 324.8964),
		vector4(140.6842, -1321.5289, 28.6976, 324.6193),
		vector4(138.4189, -1320.0251, 28.6950, 326.5188)
            }
        },
    	{
            label = 'Clinton Garage',
            type = 'car',
            pedCoords = vector4(363.2717, 296.8727, 102.5045, 250.2605),
            zone = {name = 'Clinton', x = 363.2776, y = 296.7981, z = 103.5038, l = 40, w = 50, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(374.8882, 294.4703, 102.7620, 344.3542),
		vector4(378.7696, 293.1458, 102.6819, 345.3366),
		vector4(382.6928, 292.1373, 102.6036, 343.4674),
		vector4(386.7144, 290.8940, 102.5368, 344.2289),
		vector4(390.6964, 289.9678, 102.4837, 342.1220),
		vector4(371.2613, 285.0111, 102.7434, 159.6965),
		vector4(361.1718, 293.6475, 102.9945, 68.4244),
		vector4(359.9965, 289.7683, 102.9834, 66.7306),
		vector4(374.8225, 283.6239, 102.6716, 158.4692)
            }
        },
    	{
            label = 'Duluoz Garage',
            type = 'car',
            pedCoords = vector4(-242.4728, 6187.8345, 30.4897, 4.2678),
            zone = {name = 'Duluoz', x = -244.95, y = 6199.21, z = 31.49, l = 30, w = 30, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(-247.9802, 6206.1729, 31.1401, 313.6877),
		vector4(-245.5333, 6203.7852, 31.1400, 315.5424),
		vector4(-243.1419, 6201.3916, 31.1399, 313.5717),
		vector4(-240.9136, 6199.0371, 31.1408, 314.5546),
		vector4(-238.4528, 6196.7085, 31.1403, 313.9907)
            }
        },
    	{
            label = 'Eclipse Garage',
            type = 'car',
            pedCoords = vector4(-340.8967, 268.4468, 84.5949, 356.3442),
            zone = {name = 'Eclipse', x = -337.84, y = 285.49, z = 85.25, l = 37.5, w = 37.5, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(-329.1163, 274.4040, 85.9819, 273.0096),
		vector4(-349.4191, 272.5506, 84.7508, 89.8577),
		vector4(-329.2287, 278.0049, 85.9677, 273.1199),
		vector4(-349.1834, 275.8305, 84.6926, 90.1581),
		vector4(-328.9232, 281.3888, 85.9272, 274.7086),
		vector4(-349.3327, 279.2679, 84.6082, 90.0718)
            }
        },
    	{
            label = 'Del Perro Garage',
            type = 'car',
            pedCoords = vector4(-2028.7510, -464.9650, 10.4481, 321.2039),
            zone = {name = 'Del Perro', x = -2026.89, y = -469.54, z = 11.06, l = 70, w = 70, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(-2024.3458, -472.1004, 11.0534, 139.8099),
		vector4(-2022.1272, -474.1353, 11.0509, 140.3164),
		vector4(-2019.7952, -476.1753, 11.0504, 139.9907),
		vector4(-2017.3204, -478.1375, 11.0524, 141.3380),
		vector4(-2015.0371, -480.1420, 11.0515, 142.1022),
		vector4(-2023.8433, -487.5004, 11.3519, 320.4469),
		vector4(-2026.1367, -485.4317, 11.3419, 320.0905),
		vector4(-2028.5354, -483.4524, 11.3387, 319.6821),
		vector4(-2030.8821, -481.4422, 11.3352, 319.7006),
		vector4(-2033.0912, -479.3749, 11.3185, 320.7223)
            }
        },
    	{
            label = 'Goma Garage',
            type = 'car',
            pedCoords = vector4(-1050.9347, -1411.3647, 4.4254, 346.9491),
            zone = {name = 'Goma', x = -1050.93, y = -1411.36, z = 5.43, l = 60, w = 60, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(-1056.1593, -1415.1796, 5.0765, 254.2403),
		vector4(-1048.5490, -1417.3262, 5.0755, 78.2400),
		vector4(-1057.3745, -1418.5656, 5.0766, 253.7079),
		vector4(-1049.3169, -1420.8967, 5.0768, 74.4133),
		vector4(-1058.0660, -1422.2108, 5.0760, 254.5511),
		vector4(-1050.3535, -1424.4640, 5.0766, 73.2588)
            }
        },
    	{
            label = 'East Galileo Garage',
            type = 'car',
            pedCoords = vector4(-1050.9347, -1411.3647, 4.4254, 346.9491),
            zone = {name = 'East Galileo', x = -401.46, y = 1208.91, z = 325.95, l = 60, w = 60, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(-382.8510, 1219.1663, 325.2921, 276.2115),
		vector4(-383.9760, 1215.2120, 325.2930, 276.3767),
		vector4(-384.7300, 1211.1855, 325.2933, 280.0478),
		vector4(-385.8023, 1206.7736, 325.2932, 278.8135),
		vector4(-387.2430, 1202.5359, 325.2930, 276.6887),
		vector4(-388.4814, 1198.4902, 325.2928, 278.2931),
		vector4(-389.5079, 1194.1788, 325.2929, 278.1336),
		vector4(-390.8594, 1189.9731, 325.2923, 275.4130)
            }
        },
    	{
            label = 'Zancudo Garage',
            type = 'car',
            pedCoords = vector4(1944.2686, 3764.4541, 31.2126, 295.7915),
            zone = {name = 'Zancudo', x = 1956.85, y = 3769.78, z = 32.2, l = 30, w = 30, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(1949.8231, 3759.0393, 31.8558, 210.4557),
		vector4(1953.0935, 3761.1394, 31.8545, 209.3856),
		vector4(1956.2043, 3762.8772, 31.8526, 210.5312),
		vector4(1959.6318, 3764.7449, 31.8500, 209.5455),
		vector4(1963.1046, 3766.6189, 31.8474, 210.0548)
            }
        },
    	{
            label = 'Grapeseed Garage',
            type = 'car',
            pedCoords = vector4(1695.7102, 4790.6245, 40.9214, 141.0701),
            zone = {name = 'Grapeseed', x = 1690.53, y = 4776.13, z = 41.92, l = 40, w = 20, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(1691.0275, 4788.2012, 41.5722, 270.0093),
		vector4(1690.8085, 4782.4473, 41.5723, 269.3944),
		vector4(1690.9368, 4778.4985, 41.5724, 270.7971),
		vector4(1690.7781, 4774.5278, 41.5729, 269.4594),
		vector4(1690.8492, 4770.4297, 41.5727, 268.5514),
		vector4(1690.8900, 4766.4756, 41.5727, 269.8764),
		vector4(1691.1307, 4762.5483, 41.5719, 270.4695)
            }
        },
    	{
            label = 'Popular Garage',
            type = 'car',
            pedCoords = vector4(787.5991, -1821.6053, 28.2912, 254.0588), 
            zone = {name = 'Popular', x = 794.2, y = -1816.2, z = 29.35, l = 80, w = 20, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(791.6413, -1827.5339, 28.9995, 46.7281),
		vector4(790.5675, -1833.1993, 29.0051, 43.8135),
		vector4(793.6919, -1822.3723, 29.0106, 48.6131),
		vector4(793.4067, -1815.6508, 28.9695, 47.6972),
		vector4(789.2493, -1838.6631, 29.0012, 45.8632)
            }
        },
    	{
            label = 'Vespucci Garage',
            type = 'car',
            pedCoords = vector4(-463.4440, -819.5761, 29.5654, 1.3681), 
            zone = {name = 'Popular', x = -463.65, y = -806.7, z = 30.7, l = 30, w = 50, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(-460.0537, -806.7719, 30.1011, 89.7114),
		vector4(-466.7934, -806.7192, 30.1021, 269.6973),
		vector4(-460.0170, -803.6014, 30.1036, 89.5642),
		vector4(-466.1043, -803.5804, 30.1033, 269.9584),
		vector4(-460.3808, -800.5229, 30.1057, 89.6326),
		vector4(-466.3800, -800.4584, 30.1057, 270.0334),
		vector4(-460.6237, -797.4437, 30.1086, 90.0224),
		vector4(-466.3365, -797.3253, 30.1084, 269.3112),
		vector4(-460.9889, -794.0674, 30.1117, 90.5695)
            }
        },
    	{
            label = 'Sinaloa Garage',
            type = 'car',
            job = {['cds'] = 0},
            ped = `s_m_m_strpreach_01`,
            pedCoords = vector4(-3193.7283, 832.9177, 7.9284, 127.2925), 
            zone = {name = 'cds', x = -3200.1, y = 835.47, z = 8.93, l = 25, w = 25, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(-3205.6326, 842.4164, 8.2650, 122.4114),
		vector4(-3201.4766, 835.8185, 8.2648, 123.2564),
		vector4(-3195.8706, 828.6339, 8.2649, 213.4874)
            }
        },
	{
            label = 'Royal Customs Garage',
            type = 'car',
            job = {['rocu'] = 0},
            ped = `a_m_m_hillbilly_01`,
            pedCoords = vector4(690.7728, -1107.8704, 21.4487, 282.6006), 
            zone = {name = 'rocugarage', x = 700.9, y = -1106.84, z = 22.46, l = 25, w = 22, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(702.3912, -1102.1871, 21.7824, 248.6109),
		vector4(700.5786, -1107.3359, 21.8060, 248.6520),
		vector4(698.2555, -1113.4900, 21.8614, 250.3842)
            }
	},
	{
            label = 'Taiwan Garage',
            type = 'car',
            job = {['taiwan'] = 0},
            ped = `a_m_m_hillbilly_01`,
            pedCoords = vector4(24.9834, 541.2300, 175.0276, 61.6561), 
            zone = {name = 'taiwangarage', x = 22.61, y = 544.25, z = 176.02, l = 20, w = 30, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(15.2560, 553.7686, 176.1319, 115.3784),
		vector4(6.2680, 548.3000, 174.6132, 122.7523),
		vector4(0.1948, 544.2221, 173.4193, 126.7742)
            }
	},
	{
            label = 'SHOP CENTER Garage',
            type = 'car',
            pedCoords = vector4(-933.4111, -164.9544, 40.8810, 297.4627),
            zone = {name = 'shopcenter', x = -920.87, y = -167.29, z = 41.88, l = 40, w = 55, h = 0, minZ = nil, maxZ = nil},
            spawn = {
		vector4(-924.7552,-171.7251,41.2143,28.1182),
		vector4(-927.9683,-173.3607,41.2142,27.7818),
		vector4(-921.5742,-170.1466,41.2148,26.7677)
            }

	}
}

**Comment by LukeWasTakenn** [comment]
Hmm it only happens on job garages?

Is your ox_target up to date?

**Comment by Zzeyy** [comment]
It happens only to some jobs.
ROCU and TAIWAN to be specific.

Ox Target is one version off, but that should not have an impact.

**Comment by Zzeyy** [comment]
Also I have created more than one polyzone in these places.

**Comment by Zzeyy** [comment]
Any update?

**Comment by Zzeyy** [comment]
Uhh

**Comment by LukeWasTakenn** [comment]
Both issues should be resolved now.

**Comment by Zzeyy** [comment]
What do you mean by "now"?
There's no new release.

**Comment by LukeWasTakenn** [comment]
Of course, it's possible for me to fix an issue and not push a release, who would've thought?
