### ISSUE TITLE
Question about benzo-fakeplate

### ISSUE THREAD

**Issue by Zzeyy** [LukeWasTakenn/luke_garages#125]
Is there any way to keep the ownership of a vehicle after using a fake license plate?
The script I'd like to use for this is called `benzo-fakeplate`. I would do it myself if I knew how.

**Comment by LukeWasTakenn** [comment]
I can't make compatibility with every fake plate in the existence, handling fake and real plates and how vehicles are stored with them is something which that resource should do.

My resource simply check the plate that is on the vehicle at the time it's attempting to be stored.
