### ISSUE TITLE
Better way to name addon vehicles

### ISSUE THREAD

**Issue by Zzeyy** [LukeWasTakenn/luke_garages#126]
I'll say this before I forget it. The ambulance (vanilla vehicle) has a NULL instead of the maker displayed in the garage.

I think it'd be better and easier to name addon vehicles in some config file, instead of editing two files for each addon vehicle.
Just imagine a configuration file which contains all the addon vehicles and also has a name for each individual vehicle.
That'd be awesome and I believe not so hard to code.

**Comment by Zzeyy** [comment]
So we'll be just naming the cars the hard way, okay.

**Comment by LukeWasTakenn** [comment]
No you'll be naming the cars the intended way, which is no more difficult than what you asked for.

**Comment by Zzeyy** [comment]
https://github.com/Musiker15/vehiclenames

I just fell in love with this script.

**Comment by Zzeyy** [comment]
This way I can even fix the issue with the ambulance.
