### ISSUE TITLE
job-garage (police) cant get vehicle

### ISSUE THREAD

**Issue by Marc85BPG** [LukeWasTakenn/luke_garages#129]
After paste the lines from source code instead of taking relase, now i am able to park in a job vehicle with every character.
(Before i cant store any society vehicle (police) ) 
But Now i JUST can park out with the character i bought it. Other chars have "No Vehicles in Garage)

How to fix this ? 
(i want to every employee can take out a vehicle.)
(In best case is the "owner" not a character- it should be the society by itself. Because an employee can use the car but of course not own it)

Regars

**Comment by LukeWasTakenn** [comment]
If you wish for everyone to be able to take the vehicle out you have to set the `owner` column for the vehicle to the job that you want to be able to take it out, i.e `police`.

**Comment by Marc85BPG** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/17122774/198834332-f2a1786c-d3da-4d24-bb6f-a7bb6413cd84.png)
Hope this is correct way- It works like this. 
Wonderful, how can i thank you? 


ps: in the "release" version it doesnt works like that, thats why i dont tried again, i tested this before (police/society_police)

**Comment by LukeWasTakenn** [comment]
yeah I'll push a new release soon.
