### ISSUE TITLE
Job garages (blips) still do not appear on the map

### ISSUE THREAD

**Issue by Zzeyy** [LukeWasTakenn/luke_garages#130]
![image](https://user-images.githubusercontent.com/97387354/198889992-4f7ed5a0-376f-489c-b1d7-467ae567641d.png)

This was supposedly fixed, but no, it has not.

**Config**
```
	{
            label = 'Royal Customs Garage',
            type = 'car',
            job = {['rocu'] = 0},
            ped = `a_m_m_hillbilly_01`,
            pedCoords = vector4(690.7728, -1107.8704, 21.4487, 282.6006), 
            zone = {name = 'rocugarage', x = 700.9, y = -1106.84, z = 22.46, l = 25, w = 22, h = 0, minZ = nil, maxZ = nil},
            spawns = {
		vector4(702.3912, -1102.1871, 21.7824, 248.6109),
		vector4(700.5786, -1107.3359, 21.8060, 248.6520),
		vector4(698.2555, -1113.4900, 21.8614, 250.3842)
            }
	},
```

**Comment by LukeWasTakenn** [comment]
Are you using the release or the latest commit

**Comment by Zzeyy** [comment]
2.9.0

**Comment by Zzeyy** [comment]
But I updated my client.lua to the latest commit.

**Comment by Zzeyy** [comment]
Also...

**Job Garage** `e55w211`

![image](https://user-images.githubusercontent.com/97387354/198891470-636f3e1e-2e84-42ed-95f4-5c6627f7693d.png)

**Casual Garage** `gxg63`

![image](https://user-images.githubusercontent.com/97387354/198891515-4e33718e-7987-4beb-b116-bc362e430433.png)

`vehicle_names.lua`
![image](https://user-images.githubusercontent.com/97387354/198891533-d6cd8a14-7ea7-4633-9aa5-f2e004838907.png)


I made a single edit to the `client.lua` and that's the line 418
`        local vehicleTitle = vehicleModel`

instead of
`        local vehicleTitle = vehicleMake .. ' ' .. vehicleModel`

**Comment by Zzeyy** [comment]
Why is one car displayed as it should be and another is not?

**Comment by LukeWasTakenn** [comment]
> Why is one car displayed as it should be and another is not?

The meta files for that vehicle aren't set up correctly

**Comment by Zzeyy** [comment]
No, that cannot be it.

`modelName` is defined in the script file in the resource.

**Comment by Zzeyy** [comment]
And if I know correctly then `modelName` is the same thing as `vehicleModel`, defined in the `client.lua`

**Comment by Zzeyy** [comment]
I removed the `vehicleMake` from the `client.lua` for a very good reason.

**Comment by Zzeyy** [comment]
Now I know why the garage did not appear on the map,
it's because the `minZ` and `maxZ` were not set to `nil`,
but the other garages that had these values set to `nil` did not work either,
but they do now and so does the garage I had problems with today.

**Comment by Zzeyy** [comment]
Man, I wish you could give a garage a different blip. That would be awesome.
Red garages for jobs would be better than blue.

**Comment by LukeWasTakenn** [comment]
> No, that cannot be it.

Alright dude

> And if I know correctly then modelName is the same thing as vehicleModel, defined in the client.lua

You don't know correctly

> Man, I wish you could give a garage a different blip

I'll probably make it so you can define blip values for each garage/impound

**Comment by Zzeyy** [comment]
If I don't know correctly, then how is that one car is actually displaying the name I gave it in `vehicle_names.lua`?

**Comment by Zzeyy** [comment]
Sorry, but I'm definitely not going to edit multiple files per vehicle, it would take hours.

**Comment by LukeWasTakenn** [comment]
> If I don't know correctly, then how is that one car is actually displaying the name I gave it in vehicle_names.lua?

Because it has properly defined meta values for the make and model name.

> Sorry, but I'm definitely not going to edit multiple files per vehicle, it would take hours.

Then don't download vehicles with improper meta files.

**Comment by Zzeyy** [comment]
Wow.

**Comment by Zzeyy** [comment]
What's the `vehicle_names` file for then?

**Comment by Zzeyy** [comment]
Fun fact, if I remove the name of the `e55w211` from the `vehicle_names` file then the car appears as `NULL NULL` in garages.

**Comment by Zzeyy** [comment]
So am I really supposed to set both values (maker and model) in the meta file?

**Comment by LukeWasTakenn** [comment]
> What's the vehicle_names file for then?

It adds those meta entries into the game.

> Fun fact, if I remove the name of the e55w211 from the vehicle_names file then the car appears as NULL NULL in garages.

As expected.

> So am I really supposed to set both values (maker and model) in the meta file?

Yes that's how GTA handles the names.

**Comment by Zzeyy** [comment]
But then why are we supposed to write the model name in the `vehicle names` file?

**Comment by Zzeyy** [comment]
It makes so little sense

**Comment by LukeWasTakenn** [comment]
As I've already said it adds the actual entry into the game so that the RAGE engine can recognize it and display the proper name instead of saying `NULL`.

Now please stop spamming my Issues.
