### ISSUE TITLE
Hacker protection 

### ISSUE THREAD

**Issue by icecubepiso** [LukeWasTakenn/luke_garages#27]
Check original vehprops along with model saving in database.
Prevent hackers to change vehicle model by plate 

To this "bug":

Player 1 buy BMX
Player 1 give plate number to Player 2 with cheats
Player 2 sets for another car (buffalo for example) same plate as Player 1 BMX
Player 1 will take BMX from garage
Player 1 now owns a different car (buffalo, what we use as example)

Can be used function from advancedgarages to check this, easy way to find it is search for "KickCheaters" on server side

**Comment by LukeWasTakenn** [comment]
Resolved in 1c63d1a2f916fe50eaf160e00f806ade80c36a9b.

Sorry it took me this long to do it.
