### ISSUE TITLE
NPC not showing / Double Context showing 

### ISSUE THREAD

**Issue by dougiebeatz** [LukeWasTakenn/luke_garages#30]
Hello , ive ran into two issues , as im moving away from renzuzu garages . 

the script starts but the npc at the garage wont show up untill i restart the script i am up to date on version of script 

when the NPC does spawn use tracking to click on him and it pops up two context systems which you can double your car .

**Comment by LukeWasTakenn** [comment]
Your first issue is most likely related to a bad starting order, where a resource with a dependency export starts after the garages resource and it doesn't find the export.

I don't know what could be causing the second issue.

**Comment by dougiebeatz** [comment]
Thanks for quick reply after reading a bit i moved my target system above the garages . as i read thats what needs to be done . will test that out shortly . 

ive been using ZF context , and NH context , seems like both of them are popping up at the same time , could they both be using the same export somehow ??

**Comment by LukeWasTakenn** [comment]
Yes, ZF context uses the exact same event as nh-context so that's why you're getting it to pop up twice.

**Comment by dougiebeatz** [comment]
WELLL SHIT , any ideas how i can continue to use both or just cut one out

**Comment by LukeWasTakenn** [comment]
I don't recommend you have two resources that do the same thing.

Anyways going to be closing this one now as it's solved.
