### ISSUE TITLE
Error when i enter in server,

### ISSUE THREAD

**Issue by DevMarley** [LukeWasTakenn/luke_garages#39]
![imagem](https://user-images.githubusercontent.com/36583733/149009203-57531976-5fd5-4304-ab53-80597cf28103.png)
how i can fix this?
When I turn on the server, the script starts in the console without any errors, but when I enter the server this error shows up and turns off the garages scripts. However, if I ensure, it starts working again. I have all the script versions updated.

**Comment by DevMarley** [comment]
the export 
![imagem](https://user-images.githubusercontent.com/36583733/149010135-8fc6e812-7534-43f4-be5e-ef6b92fc9856.png)

**Comment by LukeWasTakenn** [comment]
Make sure you are starting `qtarget` before starting `luke_garages` in your server.cfg

**Comment by DevMarley** [comment]
![imagem](https://user-images.githubusercontent.com/36583733/149011030-6fc853f8-8b98-44b7-abbd-d9bd9e5504f5.png)
![imagem](https://user-images.githubusercontent.com/36583733/149011083-277c0b0e-231c-4ecf-9ba4-8289b4d64cf4.png)

**Comment by DevMarley** [comment]
yeah is all right i guess i dont understand why i have this error..

**Comment by LukeWasTakenn** [comment]
Yeah that's quite strange

**Comment by DevMarley** [comment]
![imagem](https://user-images.githubusercontent.com/36583733/149011338-dc4b7215-cd57-464c-bba0-2686ca9f2d8e.png) all right in console..

**Comment by DevMarley** [comment]
![imagem](https://user-images.githubusercontent.com/36583733/149011505-dcf5001b-51f6-424c-a9cb-b6393f3929ee.png)
 when i enter in the server..

**Comment by DevMarley** [comment]
u want to see someone thing?

**Comment by LukeWasTakenn** [comment]
Not getting a console error is normal for missing export errors, I just don't know why it's happening to you when your load order looks fine.

**Comment by DevMarley** [comment]
ok thx for your time anyways ;)
