### ISSUE TITLE
Not able to store normal vehicles

### ISSUE THREAD

**Issue by Vumono** [LukeWasTakenn/luke_garages#40]
![image](https://user-images.githubusercontent.com/87247208/149010592-f7ddf3bf-465a-4dd2-a0b3-70740e81135f.png)
![image](https://user-images.githubusercontent.com/87247208/149010624-00a84e19-8fda-42b0-88eb-e017f6b9c07d.png)
![image](https://user-images.githubusercontent.com/87247208/149011081-f5b65d14-7189-4f19-aed3-58dc8cab1fcf.png)

Im not able to store cars in a normal garage, when storing a car in job garage the car disappears and doesn't show in the menu. It is saved in `owned_vehicles` tho. Had this problem with the 2.4.0 version aswell.

**Comment by LukeWasTakenn** [comment]
Why is your job column a 0 what the hell, that's probably the reason. I'm doing a check for NULL or `civ`

**Comment by Vumono** [comment]
Cool, changing that in the database works. Will take a look at my vehicleshop script then.
