### ISSUE TITLE
Still not able to store job vehicle in normal garage

### ISSUE THREAD

**Issue by Vumono** [LukeWasTakenn/luke_garages#41]
![image](https://user-images.githubusercontent.com/87247208/149126279-a1b5f38f-09e8-44ef-877b-9ef9e7bb3245.png)
Job now is automatically called civ in database instead of 0, still says cannot park your job vehicle here. I can pull out some cars tho. Just not depositing them back. 
![image](https://user-images.githubusercontent.com/87247208/149126342-e0ecf8f8-0753-4f29-aca4-678132872908.png)
I can put the cars in the garage of my current job, but then it doesnt show up in that list.
![image](https://user-images.githubusercontent.com/87247208/149126730-b82f7457-669c-4800-87f3-d1f30c3793dd.png)

**Comment by LukeWasTakenn** [comment]
Line 547 in clinet.lua:
`if type(doesOwn) == 'table' then return ESX.ShowNotification("You can't store your job vehicle here") end`

I guess I can maybe make it a config option or something.

**Comment by viper052186** [comment]
try to make all garage has job = '',

like this

type = 'car',
job = '',


for me it works.

**Comment by LukeWasTakenn** [comment]
what?

**Comment by Vumono** [comment]
Well, that doesn't work if you have specific garages for certain jobs only.

**Comment by Vumono** [comment]
I used a fresh download, vehicleshop sets the job to civ in owned_vehiclestable, but it still says cant store job vehicle here

**Comment by LukeWasTakenn** [comment]
It's probably going to be server side job checks then, I'll look into it.

**Comment by LukeWasTakenn** [comment]
This should now be resolved, though you are still not able to park job vehicles in civ garages so let me know if you'd maybe want this as a config option or something.
