### ISSUE TITLE
REQUEST // Impound

### ISSUE THREAD

**Issue by frazz1234** [LukeWasTakenn/luke_garages#42]
This is possible to put a impound only police officer and mechanic can store full a time chossing and can only pull out after the time whit an big invoice choose by the polce !? Thanks

**Comment by LukeWasTakenn** [comment]
This would require a lot of rewriting to split the impounds which I have no intention of doing.

The closest thing to this that I had in mind was providing an export function for impounding that would let police or mechanics choose a price the vehicle should be impounded for.
