### ISSUE TITLE
Impound labels

### ISSUE THREAD

**Issue by Fleevo73** [LukeWasTakenn/luke_garages#43]
Unfortunately there isn't a way to change the name of the map blip of the impound from "Car Impound lot" or it breaks the whole garage system, unless I'm spud I've tried just about everything. Id just really like to put it to my designated name. :(

**Comment by LukeWasTakenn** [comment]
Yeah I can add a label property for impounds.

**Comment by Fleevo73** [comment]
Please do, would really be much appreciated, Im sure there is others who would like to do the same. Also how can I go about what changing the Blip icon? @LukeWasTakenn

**Comment by LukeWasTakenn** [comment]
Change the value in `SetBlipSprite` on the client

**Comment by LukeWasTakenn** [comment]
Implemented in latest commit

**Comment by Fleevo73** [comment]
Appreciate that, how can I go about changing it from "Car Impound lot"?
