### ISSUE TITLE
Impound does not give you your owned car

### ISSUE THREAD

**Issue by BizkitCrackers** [LukeWasTakenn/luke_garages#44]
Hi,

When taking a car out of the impound it gives you the car but it is not the same plate.
It gives you the car as if it was spawned with /car instead of giving you the owned car plate.

**Comment by BizkitCrackers** [comment]
![image](https://user-images.githubusercontent.com/95104646/150019686-00967ecc-e99f-453d-9609-14a128a16d9c.png)

**Comment by BizkitCrackers** [comment]
![image](https://user-images.githubusercontent.com/95104646/150019722-0b3341f5-caf5-4fab-a9a7-c8d234b98132.png)

**Comment by BizkitCrackers** [comment]
Thats an example of the Asbo

**Comment by BizkitCrackers** [comment]
And the garage itself is showing the car as out of the garage

**Comment by BizkitCrackers** [comment]
![image](https://user-images.githubusercontent.com/95104646/150021258-b82bb6be-4bb6-4abb-a9ea-02c8e5e8ac97.png)

I bought the asbo from the dealership and put them in the garage and it still shows not in garage

**Comment by LukeWasTakenn** [comment]
Weird, can I see the data in your `owned_vehicles` table?

**Comment by BizkitCrackers** [comment]
Im leo532, the guy on cfx who had issues with the seeing all players.

**Comment by LukeWasTakenn** [comment]
I don't see a `health` nor `garage` column in your table

**Comment by BizkitCrackers** [comment]
Too right, I dont know why its not there as i added the sql, reinstalled everything and imported the sql again and it has worked.

Tested it now and everything is working perfect!!

Thanks man quick support too :D
