### ISSUE TITLE
Restricting the Impound Lots to a specific job for player managment

### ISSUE THREAD

**Issue by ItzTrivial** [LukeWasTakenn/luke_garages#45]
I saw players manage the impound on many server and it would actually be crazy if there would be an option for only one job to see all the players impounded cars, so the players would actually have to go to the impound manager to get their cars.

Since Im not very familiar with complex database work I dont know if that would be possible, but: To make it easier to keep up with tons of impounded cars there could be a context-menu only showing the players IDs, who are really online with a submenu for each ID to their impounded cars.

I hope that my english is advanced enough to give you an idea of what Im trying to suggest here.

**Comment by LukeWasTakenn** [comment]
Even if I implement something like this, which I'm not even sure I would it would not be anytime soon but rather down in the future maybe.
