### ISSUE TITLE
Add Job in config Garage didn't work

### ISSUE THREAD

**Issue by KrisnaCahya** [LukeWasTakenn/luke_garages#46]
hi
when I add a job parameter in config.lua the garage function doesn't work immediately but when there is no job it can be used, please help, is there something wrong when I put the job in the config below

{
            label = 'Caste Garage', -- name that will be displayed in menus
            type = 'car', -- can be 'car', 'boat' or 'aircraft',
            job = 'caste', -- Set garage to be only accessed and stored into by a job (Optional)
            ped = `s_m_y_airworker`, -- Define the model model you want to use for the garage (Optional)
            pedCoords = vector4(-803.88, 325.68, 84.72, 289.84), -- Ped MUST be inside the create zone
            zone = {name = 'castegarasi', x = -803.85, y = 325.64, z = 85.7, l = 20, w = 20, h = 0, minZ = 84.7, maxZ = 88.7},
            spawns = { -- You can have as many as you'd like
                vector4(-800.2, 333.36, 85.28, 179.04)
            }
        },

**Comment by KrisnaCahya** [comment]
![image](https://user-images.githubusercontent.com/78995521/150063883-0f28386a-c175-4b03-92e9-0e93e9ecc707.png)

**Comment by LukeWasTakenn** [comment]
Do the included police and ambulance garages work?

**Comment by LukeWasTakenn** [comment]
You can only store job vehicles in the garages that have the same job as the vehicle, if that's what you're asking.

**Comment by KrisnaCahya** [comment]
That's not it, I can't store the vehicle when I've set the job according to config.lua

**Comment by KrisnaCahya** [comment]
![image](https://user-images.githubusercontent.com/78995521/150235535-775c4b05-82f3-4d82-b3c5-6b137ea5da7f.png)

**Comment by LukeWasTakenn** [comment]
Does your vehicle job name match the garages job name?
