### ISSUE TITLE
Impound can't show the impounded vehicle 

### ISSUE THREAD

**Issue by KrisnaCahya** [LukeWasTakenn/luke_garages#47]
Hi
I want to ask about the database where it says stored 0 but on impound it says no vehicle in impound
is there something wrong? even though it should be safe but after upgrading the new version it turned out like this and I tried again to try using the previous version it's still the same since the version update
Thank you a

![image](https://user-images.githubusercontent.com/78995521/150277243-3ca58ab9-6c06-4ea3-9f90-ae54df4746c2.png)

**Comment by LukeWasTakenn** [comment]
For a vehicle to be in impound it must not exist currently in the game world and have it's stored column set to 0
