### ISSUE TITLE
Custom vehicle is displaying NULL NULL. 

### ISSUE THREAD

**Issue by Vumono** [LukeWasTakenn/luke_garages#48]
Custom vehicle is displaying NULL NULL in garage. Looks like it doesnt get the Label text for some reason.
![image](https://user-images.githubusercontent.com/87247208/150357004-9f36b367-0f92-4b07-b82e-96b204a72216.png)
![image](https://user-images.githubusercontent.com/87247208/150357043-ab0b9b7e-d6ad-4435-b7a1-36a60878245a.png)
![image](https://user-images.githubusercontent.com/87247208/150357136-7c6aa66e-70c0-4d63-8b9b-d7035d5520d9.png)

**Comment by LukeWasTakenn** [comment]
Is this the only custom vehicle you have trouble with displaying the name?

**Comment by Vumono** [comment]
No all of them, I'll try adding even more custom ones to see if they do work

**Comment by Vumono** [comment]
![image](https://user-images.githubusercontent.com/87247208/150394703-af7a7e31-4754-487d-a881-06224b28819b.png)
Some parts do show up now

**Comment by LukeWasTakenn** [comment]
hmm I wonder if that's just the vehicle not having correct data or something

**Comment by Vumono** [comment]
It is able to spawn in via the menu tho, with same spawnname

**Comment by Vumono** [comment]
Vehicles.meta wasnt correctly loaded

**Comment by Vumono** [comment]
Vehicles.meta wasnt correctly loaded
