### ISSUE TITLE
Cannot add new garages

### ISSUE THREAD

**Issue by DistrictZion** [LukeWasTakenn/luke_garages#49]
I cannot add new garages for some reason. Script starts fine with all the previous garages but the new garages don't show up after adding in config..

**Comment by LukeWasTakenn** [comment]
All the garages are indexed on resource startup so it doesn't make sense that some work and some don't.

Maybe a syntax error?

**Comment by DistrictZion** [comment]
There isnt any syntax errors. Thats what confuses me. The same thing works at the default garages but nothing shows up in added ones

**Comment by LukeWasTakenn** [comment]
Can you put your config file into a pastebin and link it please?

**Comment by DistrictZion** [comment]
https://pastebin.com/5KR41Kwc

**Comment by DistrictZion** [comment]
As you can see, I have added a garage. Everything else works except the new one i add.

**Comment by DistrictZion** [comment]
The blip shows but no ped/functionality

**Comment by LukeWasTakenn** [comment]
Yeah sorry I just now got around checking this, anyways here's your issue
![image](https://user-images.githubusercontent.com/39926192/151695216-374acf8f-cb70-4fc3-8174-d557fb3efe3b.png)

**Comment by DistrictZion** [comment]
Oops .. Thanks

**Comment by DistrictZion** [comment]
I am new to PolyZone and qtarget. Excuse me and please remove this thread. Thanks for your responses

**Comment by LukeWasTakenn** [comment]
It's all good.
