### ISSUE TITLE
Impound Issue

### ISSUE THREAD

**Issue by Asmoddy** [LukeWasTakenn/luke_garages#51]
When I tried impounding car when I'm on a police job or mechanic, it doesn't show on the impound garage.

**Comment by Vumono** [comment]
If you use the default esx_policejob, the vehicle just gets deleted and not added into the impound

**Comment by LukeWasTakenn** [comment]
> If you use the default esx_policejob, the vehicle just gets deleted and not added into the impound

That's really strange though, the function in that resource does exactly the same thing as `/dv` command, does that send the vehicle to the impound?

**Comment by kagesamo** [comment]
I have the same issue.... Impounded vehicles are not shown in the impound.

**Comment by LukeWasTakenn** [comment]
I just tested this again with -cl2, with both police and mechanic jobs.

I guess make sure that your esx and those jobs are up to date.

**Comment by kagesamo** [comment]
Hello Luke. Just updated esx legacy to version 1.5 (last one), myslq-async to oxmysql and the jobs and nothing. Database shows the value 0 on stored column. Dont know what its happening.

**Comment by LukeWasTakenn** [comment]
Artifacts should be fine, if stored column is 0 then it surely has to do something with deleting the vehicle from the world which is really weird.

**Comment by LukeWasTakenn** [comment]
If you add `print(GetVehicleNumberPlateText(vehicle))` here (above the break line) and impound the vehicle, does the plate of the vehicle you just impounded print out in the server console?
https://github.com/LukeWasTakenn/luke_garages/blob/673a7ee4efbeb2e2e9bfe9b8fb5c47f4cbd35aeb/server/server.lua#L72-L73

**Comment by kagesamo** [comment]
It does not print

**Comment by LukeWasTakenn** [comment]
> It does not print

Can I see your `owned_vehicles` table columns and the data?

**Comment by kagesamo** [comment]
![image](https://user-images.githubusercontent.com/28874080/154860905-85fa2512-466e-4b56-b215-4f4bb2bb8178.png)
![image](https://user-images.githubusercontent.com/28874080/154860936-26964ca5-f2aa-4a70-8dcb-46d93e04f70d.png)

**Comment by LukeWasTakenn** [comment]
Yeah your data looks as it should, so weird though, you not getting a print there means that the vehicle isn't in the world so I literally have 0 idea why that is happening.

I'm assuming mechanic impounding has the same results

**Comment by kagesamo** [comment]
Yes you right. Mechanic impound has the same result.

**Comment by kagesamo** [comment]
I will pray that you can find a workaround for this problem because I love your script and I want to implement it on the server. :D

**Comment by kagesamo** [comment]
I have news. I tried version 2.0.0 and its working

**Comment by LukeWasTakenn** [comment]
> I have news. I tried version 2.0.0 and its working

A lot of code changed since then. Can you make a server side event in the police job that triggers when you press the impound button in the menu which is going to just run the `DeleteEntity` native with the vehicle passed as an argument?

**Comment by kagesamo** [comment]
my God. You're asking me something very complicated for me xD. Sorry i cant :(

**Comment by LukeWasTakenn** [comment]
> my God. You're asking me something very complicated for me xD. Sorry i cant :( I'm embarrassed by my lack of experience

In the client folder of esx_policejob open `main.lua`, find a function called `ImpoundVehicle` (all the way at the bottom of the file) and make it look like this:
```lua
function ImpoundVehicle(vehicle)
	--local vehicleName = GetLabelText(GetDisplayNameFromVehicleModel(GetEntityModel(vehicle)))
	TriggerServerEvent('impoundVehicle', vehicle)
	-- ESX.Game.DeleteVehicle(vehicle)
	-- ESX.ShowNotification(_U('impound_successful'))
	currentTask.busy = false
end
```

After doing that go into the server folder and open `main.lua` there, at the very top of the file add:
```lua
RegisterNetEvent('impoundVehicle', function(vehicle)
	print('deleted')
	DeleteEntity(vehicle)
end)
```
Then try impounding the vehicle, you should get the print in your server console and the vehicle should disappear, after that check the impound.

**Comment by kagesamo** [comment]
![image](https://user-images.githubusercontent.com/28874080/154866672-fe15a2f9-1952-496d-8908-436315803f11.png)
The car did not disappear.

**Comment by LukeWasTakenn** [comment]
Interesting 🤔 

But yeah scrap that, I'll keep looking into the issue to see if I can replicate it myself and then fix it

**Comment by kagesamo** [comment]
I sincerely appreciate all the time you spent trying to help me with this problem. I'll keep an eye out for future updates. Best regards.

**Comment by kagesamo** [comment]
Last working release is 2.3.1 but has the problem of duplicating vehicles if they are far from the impound. Just for knowledge.

**Comment by kagesamo** [comment]
Hello Luke. I have news. I made a new server (all default) and tested the latest version of your garage and it works, at least with gta cars. I'm still trying to figure out what caused it not to work before, but as soon as I find out I'll let you know.

**Comment by viper052186** [comment]
Also me, i face problems in impounding..it is not showing

**Comment by viper052186** [comment]
![image](https://user-images.githubusercontent.com/70097175/167053618-9820ba70-3aa8-4679-94db-7408486dcd11.png)
I notice that if there is car insde the polyzone of impounding...the cars appear in impound...but if there is no cars inside polyzone..impound selection not appear.
![image](https://user-images.githubusercontent.com/70097175/167053727-cad2b742-c232-499c-b174-765ab563e52a.png)

**Comment by LukeWasTakenn** [comment]
I've tried it the way you described it and it didn't make a difference at all, I still can't reproduce this and I've tried on at least 3 different ESX servers so I am really not sure what is going on.

**Comment by viper052186** [comment]
Boss, i try the latest version... still the same, you need a car inside the polyzone so that the car will appear on the list.

if there is no car inside polyzone...list will be empty..

**Comment by viper052186** [comment]
https://streamable.com/tghfj6

**Comment by viper052186** [comment]
> Hello Luke. I have news. I made a new server (all default) and tested the latest version of your garage and it works, at least with gta cars. I'm still trying to figure out what caused it not to work before, but as soon as I find out I'll let you know.

Hi there, what you did on that?

**Comment by kagesamo** [comment]
Hi. I just made a new esx server, all standard with no external scripts. But now I have another problem since I updated to the new release of luke_garage which uses ox_lib instead of zf_context. Whenever I enter the server my fivem crashes. If I remove ox_lib I have no problem.

**Comment by LukeWasTakenn** [comment]
> Boss, i try the latest version... still the same, you need a car inside the polyzone so that the car will appear on the list.
> 
> if there is no car inside polyzone...list will be empty..

Still can't reproduce, the vehicle goes to the impound properly after impounding it, I honestly have no clue how this happens to some people.

![image](https://user-images.githubusercontent.com/39926192/168690620-1470262f-eb66-4be2-a3f3-44bdde72b2e7.png)

**Comment by katotekii** [comment]
you refer to `mahanmoulaei` fix?

**Comment by katotekii** [comment]
> you refer to `mahanmoulaei` fix?

his solution also works, just tested
