### ISSUE TITLE
arg 'garage' is always nil and I don't see point for chaning garage to 'none'

### ISSUE THREAD

**Issue by katotekii** [LukeWasTakenn/luke_garages#53]
https://github.com/LukeWasTakenn/luke_garages/blob/4c0f1ac18e996a5b01c6ac35776324d2170fd67c/server/server.lua#L114

**Comment by LukeWasTakenn** [comment]
How is it always nil...?

Also I don't remember why I'm setting the garage to 'none' lol

**Comment by katotekii** [comment]
in TriggerServerEvent('luke_garages:ChangeStored', svData.plate, false) there is 2 args, 3rd should be garage
(currentGarage.zone.name).

**Comment by LukeWasTakenn** [comment]
ah, yeah there's no need to pass it in that trigger because the vehicle is being spawned and I don't really need to care about the garage it's being spawned from
