### ISSUE TITLE
Not saving fuel

### ISSUE THREAD

**Issue by Cloud10Dev** [LukeWasTakenn/luke_garages#54]
Hey, firstly thanks for this really good script!

Im using it but when i take cars off it doesnt save the fuel

**Comment by LukeWasTakenn** [comment]
Run the export of the fuel resource you are using when spawning the vehicle

**Comment by Cloud10Dev** [comment]
Im using rv_fuel and i dont find the export  option. Even on the garage i dont see where i can add it

**Comment by LukeWasTakenn** [comment]
the resource you use must use some kind of event or export to apply fuel, call it in the `SetVehicleMods` event
