### ISSUE TITLE
BUG - Owner change/does not save

### ISSUE THREAD

**Issue by DistrictZion** [LukeWasTakenn/luke_garages#58]
Sometimes for some players, the garage says they don't own the vehicle. This does not happen to everyone. 
Also, there are cases where an owned players car gets saved as another player's car.

**Comment by DistrictZion** [comment]
I realized this happens in very specific situations where the car is bought from vehicleshop. I changed it (insert to owned_vehicles) to have "stored "and "garage" values but it still keeps happening. 

Also I'm attaching another error I am facing

**Comment by DistrictZion** [comment]
https://i.imgur.com/SLCXMqy.png

**Comment by LukeWasTakenn** [comment]
Can I see your `owned_vehicles` table?

also I have no idea what's going on in that screenshot, seems like maybe an issue with plate trimming?

**Comment by DistrictZion** [comment]
![image](https://user-images.githubusercontent.com/78443434/153088152-a61e04e7-0349-425e-b641-0cd5b7744350.png)

**Comment by DistrictZion** [comment]
The DoVehicleDamage is not working. I can't quite figure it out either

**Comment by LukeWasTakenn** [comment]
Your health column appears to have different kinds of data in it, also different data type though I think that doesn't matter too much, same for `garage` column.

**Comment by DistrictZion** [comment]
Oh yeah. I will make those changes and see. Also, the garage value I gave so the cars go to main garage any time there is an addition in the database.

**Comment by vRhynos** [comment]
> Sometimes for some players, the garage says they don't own the vehicle. This does not happen to everyone. Also, there are cases where an owned players car gets saved as another player's car.

I have the same problem! some player can spawn other player car.

**Comment by LukeWasTakenn** [comment]
Yeah it could be, this is going to be a weird issue though.

The way it works currently is when you spawn a vehicle, the player that gets ownership of it will trigger the function that applies the correct props for that vehicle so there could be something weird happening.

**Comment by vRhynos** [comment]
I don't have any idea for fix this.. :(

**Comment by LukeWasTakenn** [comment]
@vRhynos You said you were able to resolve this issue, any update on this?

**Comment by LukeWasTakenn** [comment]
This should be resolved with 0889d58200b2065d592fecba36dc5c5578ffee95

Please let me know if the issue persists.
