### ISSUE TITLE
Randomly spawns other players vehicle

### ISSUE THREAD

**Issue by Janerdz** [LukeWasTakenn/luke_garages#59]
When garage is being used simultaneously it randomly gives you other players owned vehicles. Sometimes it gives the same car with different mods or plate number.

**Comment by LukeWasTakenn** [comment]
Seems to be a duplicate of #58

**Comment by LukeWasTakenn** [comment]
Can I see your columns in your `owned_vehicles` table?

**Comment by LukeWasTakenn** [comment]
This should be resolved with 0889d58200b2065d592fecba36dc5c5578ffee95

Please let me know if the issue persists.

**Comment by LukeWasTakenn** [comment]
Do you only see your vehicles in the garage or do you see other player's vehicles as well?

**Comment by Janerdz** [comment]
It only shows your personal owned vehicles on the list, but when you spawn it still randomly spawn other players vehicle.

**Comment by LukeWasTakenn** [comment]
> > Can I see your columns in your `owned_vehicles` table?
> 
> owner, plate, vehicle, type, job, model, stored, garage, health

Can I see the data? You can blur the identifiers if you want

**Comment by Janerdz** [comment]
> 

I've uploaded the SQL that I exported for your reference. Thank you!

[https://justpaste.it/8q3pz](url)

**Comment by LukeWasTakenn** [comment]
Yeah the data looks good, if you find a consistent way to replicate this issue please let me know, otherwise there's not much I can do to reproduce and fix this so I'll keep an eye open on this one.

**Comment by Janerdz** [comment]
> Yeah the data looks good, if you find a consistent way to replicate this issue please let me know, otherwise there's not much I can do to reproduce and fix this so I'll keep an eye open on this one.

It happens randomly. But I will try to replicate it. I'll keep you posted. Thank you!

**Comment by Janerdz** [comment]
As of today I still can't replicate the bug. It is just random.

**Comment by frazz1234** [comment]
no fix? we are gonna have to change for an other script in that case and i dont want :(

**Comment by LukeWasTakenn** [comment]
I'd love to fix it, though that's made difficult by the fact that I don't get this issue at all and can't reproduce it.

Hence the `help wanted` tag.

**Comment by Janerdz** [comment]
> no fix? we are gonna have to change for an other script in that case and i dont want :(

Me too. I really love this script. And I don't want to change it. lol

**Comment by frazz1234** [comment]
i think just add a big wait between the time the car is  spawnng or something ?

**Comment by frazz1234** [comment]
its like the car spawn before he run the database and sometimes cause an issue

**Comment by Janerdz** [comment]
ill try to make the wait script to 1 second. I will update you if this resolves the issue

**Comment by Janerdz** [comment]
Update: still the same bug. Tried adding 1000 on wait.

**Comment by LukeWasTakenn** [comment]
Can do me a favor and add `print(ESX.DumpTable(svData.vehicle))` above `ESX.SetVehicleMods` and take a screenshot of the print in the F8 console when the issue occurs

https://github.com/LukeWasTakenn/luke_garages/blob/e30a177a58698335be96fb5e3cbea271e9dc8d79/client/client.lua#L289-L295

**Comment by Janerdz** [comment]
Ok. I'll get back to you.

**Comment by LukeWasTakenn** [comment]
Should be resolved in #71.

Reopen the issue if it isn't.
