### ISSUE TITLE
Hiding the car

### ISSUE THREAD

**Issue by TheZahamar** [LukeWasTakenn/luke_garages#60]
Hi there is one small problem when I buy a car at a car dealership it adds it to the database but it can't be hidden because the model is added by name and not by hash. Do you have any solution? Sorry for my english.

**Comment by LukeWasTakenn** [comment]
What do you mean by can't be hidden because it's added by name and not by hash?

**Comment by TheZahamar** [comment]
You cannot store the vehicle because it is added to the database as a model name, not a hash and says you are not the owner

**Comment by LukeWasTakenn** [comment]
So what do you want me to do about this?

It's not an issue related to my resource.

**Comment by TheZahamar** [comment]
I am using esx_vechicleshop from esx_legacy

**Comment by LukeWasTakenn** [comment]
So am I, it works fine.
