### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by frazz1234** [LukeWasTakenn/luke_garages#61]
txt = Locale('plate') .. ': ' .. v.plate .. ' <br>' .. Locale('garage') .. ': ' .. GetGarageLabel(v.garage),
![20220221203349_1](https://user-images.githubusercontent.com/66176776/155047230-d4ef283f-1e86-469a-8b22-33b074d606ef.jpg)

**Comment by frazz1234** [comment]
was going very well until.. i dont fucking know 40 pers on the serv

**Comment by LukeWasTakenn** [comment]
Seems like you don't have a label set for one of the garages or something

**Comment by frazz1234** [comment]
looks like having the same trouble whit some client, lost the acces to the garage sometime.... !

**Comment by frazz1234** [comment]
happen whitout any .. do fuckall... ! a restart server is necessary ... and not fixing everything..

**Comment by frazz1234** [comment]
We found a fix, so the trouble is whit the 'none' in the DB when you out a car... since we put stored 0 and garage legion, everything is fix. you should only go whit the stored 0 or 1 for know if the car is outside or inside the garage
