### ISSUE TITLE
Support for society vehicles

### ISSUE THREAD

**Issue by Zzeyy** [LukeWasTakenn/luke_garages#68]
Hi,

I added some cars in the police society, so the players can use some cars,
but when they get deleted they don't appear in the impound, probably because it's not supported.
Is there anything I can do in order to show the police cars in the impound?
If no, will you be adding support for it?

**Comment by LukeWasTakenn** [comment]
They are supported.

https://github.com/LukeWasTakenn/luke_garages/blob/e30a177a58698335be96fb5e3cbea271e9dc8d79/server/server.lua#L63

Are you deleting the vehicles by impounding them with the police job? Cause that is a currently open issue.

**Comment by Zzeyy** [comment]
No, I deleted the vehicle with /dv command.
But I set the vehicle owner to "police",
so I don't know if that would make any difference

**Comment by LukeWasTakenn** [comment]
Well yeah setting the owner to `police` where the query looks for player identifier won't work.

Someone PRed full support for society vehicles but they haven't updated the PR so I'll probably end up implementing this fully myself when I get to it.

**Comment by LukeWasTakenn** [comment]
Supported as of acdd493bf739a444a58e6d01184ecc66080681ae.

Need feedback on this.

**Comment by Zzeyy** [comment]
You'll get it, you're the best man.
