### ISSUE TITLE
Can take car from garage multiple times

### ISSUE THREAD

**Issue by malikbambini** [LukeWasTakenn/luke_garages#73]
I find issue in latest update.

Script doesnt recognize u take out car from garage and u can take same car multiple times.

**Comment by LukeWasTakenn** [comment]
Any repro steps for this? Cause I'm not getting this issue.

Also maybe it's just your stored column not changing for some reason?

**Comment by malikbambini** [comment]
artifact 5303
gamebuild 2545

i don't have any errors in tx admin.

stored column changing only if i put car to garage (from 0 to 1), otherwise not.

https://streamable.com/r321e
![Zrzut ekranu (130)](https://user-images.githubusercontent.com/100540104/160239495-a71f0906-3039-4e94-9fd6-a93320ff046e.png)
g

**Comment by LukeWasTakenn** [comment]
Right I think I see the issue:

Can you try changing this line:
https://github.com/LukeWasTakenn/luke_garages/blob/438bfb60702ecff9fdc5af78abee2431f7487c6e/client/client.lua#L229

to this:
```lua
TriggerServerEvent('luke_garages:ChangeStored', value.plate, false, nil)
```

And let me know if that fixes it for you?

**Comment by malikbambini** [comment]
Yep. That solved problem.

Thank you!

**Comment by LukeWasTakenn** [comment]
Cool I'll patch it.
