### ISSUE TITLE
After Update, got this error,

### ISSUE THREAD

**Issue by frazz1234** [LukeWasTakenn/luke_garages#76]
After a restart server, no vehicule or anymore in the garage (thid eye)
but in sql i can see they are in legion

F8:
![20220327152816_1](https://user-images.githubusercontent.com/66176776/160297544-5bda8618-f38f-4f41-a170-13989a1d3a89.jpg)

**Comment by LukeWasTakenn** [comment]
What does your `owned_vehicles` table look like?

**Comment by frazz1234** [comment]
CREATE TABLE `owned_vehicles` (
  `owner` varchar(60) NOT NULL,
  `plate` varchar(12) NOT NULL,
  `vehicle` longtext NOT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'car',
  `job` varchar(20) NOT NULL DEFAULT 'civ',
  `category` varchar(50) DEFAULT NULL,
  `name` varchar(60) NOT NULL DEFAULT 'Unknown',
  `fuel` int(11) NOT NULL DEFAULT 100,
  `stored` tinyint(1) NOT NULL DEFAULT 0,
  `image` longtext DEFAULT NULL,
  `health` text DEFAULT NULL,
  `last_garage` varchar(40) DEFAULT 'NULL',
  `garage` varchar(40) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `owned_vehicles`
--

INSERT INTO `owned_vehicles` (`owner`, `plate`, `vehicle`, `type`, `job`, `category`, `name`, `fuel`, `stored`, `image`, `health`, `last_garage`, `garage`) VALUES
('662689f1c506ddac941a41b5604e40d3209a5507', 'FMM 094', '{\"modTurbo\":false,\"modRightFender\":-1,\"wheels\":1,\"modFender\":-1,\"modRoof\":-1,\"modPlateHolder\":-1,\"modDashboard\":-1,\"color1\":2,\"modSpoilers\":-1,\"neonEnabled\":[false,false,false,false],\"modSuspension\":-1,\"modHorns\":-1,\"xenonColor\":255,\"modStruts\":-1,\"modSteeringWheel\":-1,\"plateIndex\":0,\"modArchCover\":-1,\"modHood\":-1,\"bodyHealth\":1000.0,\"dirtLevel\":3.0,\"modHydrolic\":-1,\"modRearBumper\":-1,\"windowTint\":-1,\"modExhaust\":-1,\"modOrnaments\":-1,\"modTrunk\":-1,\"plate\":\"FMM 094\",\"modLivery\":-1,\"modTank\":-1,\"engineHealth\":1000.0,\"modDial\":-1,\"modFrontBumper\":-1,\"modDoorSpeaker\":-1,\"tankHealth\":1000.0,\"modArmor\":-1,\"modFrame\":-1,\"modGrille\":-1,\"pearlescentColor\":2,\"tyreSmokeColor\":[255,255,255],\"color2\":70,\"modSeats\":-1,\"modSideSkirt\":-1,\"fuelLevel\":65.0,\"model\":-984254554,\"modShifterLeavers\":-1,\"modAPlate\":-1,\"modWindows\":-1,\"modSpeakers\":-1,\"modTrimA\":-1,\"modXenon\":false,\"modBackWheels\":-1,\"modEngineBlock\":-1,\"modAirFilter\":-1,\"extras\":[],\"modTransmission\":-1,\"modFrontWheels\":-1,\"neonColor\":[255,0,255],\"modEngine\":-1,\"wheelColor\":156,\"modSmokeEnabled\":false,\"modTrimB\":-1,\"modVanityPlate\":-1,\"modBrakes\":-1,\"modAerials\":-1}', 'car', 'civ', NULL, 'Unknown', 100, 1, NULL, NULL, 'legion', 'legion'),
('662689f1c506ddac941a41b5604e40d3209a5507', 'FWX 026', '{\"color1\":29,\"modSpoilers\":-1,\"modArmor\":-1,\"modFender\":-1,\"color2\":111,\"windowTint\":-1,\"modXenon\":false,\"tankHealth\":1000.0,\"modGrille\":-1,\"modRoof\":-1,\"modAPlate\":-1,\"modHorns\":-1,\"modFrontBumper\":-1,\"modAirFilter\":-1,\"modHydrolic\":-1,\"modSteeringWheel\":-1,\"plate\":\"FWX 026\",\"engineHealth\":1000.0,\"model\":931280609,\"extras\":[],\"neonEnabled\":[false,false,false,false],\"wheels\":0,\"modOrnaments\":-1,\"pearlescentColor\":7,\"modDoorSpeaker\":-1,\"wheelColor\":5,\"modRightFender\":-1,\"bodyHealth\":1000.0,\"dirtLevel\":2.0,\"modExhaust\":-1,\"modSuspension\":-1,\"plateIndex\":0,\"modBackWheels\":-1,\"modDashboard\":-1,\"modEngineBlock\":-1,\"modSpeakers\":-1,\"modAerials\":-1,\"xenonColor\":255,\"modWindows\":-1,\"modRearBumper\":-1,\"modTrimB\":-1,\"modArchCover\":-1,\"modShifterLeavers\":-1,\"modHood\":-1,\"modFrontWheels\":-1,\"modTrunk\":-1,\"modStruts\":-1,\"modTrimA\":-1,\"modDial\":-1,\"modSideSkirt\":-1,\"fuelLevel\":100.0,\"modVanityPlate\":-1,\"modPlateHolder\":-1,\"modTurbo\":false,\"tyreSmokeColor\":[255,255,255],\"modTank\":-1,\"modFrame\":-1,\"modTransmission\":-1,\"modBrakes\":-1,\"modSmokeEnabled\":false,\"modLivery\":-1,\"neonColor\":[255,0,255],\"modEngine\":-1,\"modSeats\":-1}', 'car', 'civ', NULL, 'Unknown', 100, 1, NULL, NULL, 'legion', 'none'),
('662689f1c506ddac941a41b5604e40d3209a5507', 'GSO 367', '{\"modTrimA\":-1,\"modWindows\":-1,\"modAirFilter\":-1,\"modDashboard\":-1,\"modFrontWheels\":-1,\"modAerials\":-1,\"modTank\":-1,\"modSpeakers\":-1,\"modEngine\":-1,\"modHood\":-1,\"modSuspension\":-1,\"modSpoilers\":-1,\"windowTint\":-1,\"modTrimB\":-1,\"bodyHealth\":1000.0,\"wheelColor\":13,\"neonColor\":[255,0,255],\"modBrakes\":-1,\"modXenon\":false,\"modRightFender\":-1,\"tyreSmokeColor\":[255,255,255],\"modHorns\":-1,\"color2\":13,\"modDoorSpeaker\":-1,\"modDial\":-1,\"modSideSkirt\":-1,\"color1\":0,\"modShifterLeavers\":-1,\"modHydrolic\":-1,\"modFrame\":-1,\"dirtLevel\":6.0,\"modExhaust\":-1,\"pearlescentColor\":134,\"modBackWheels\":-1,\"modGrille\":-1,\"modOrnaments\":-1,\"modArmor\":-1,\"modPlateHolder\":-1,\"tankHealth\":1000.0,\"extras\":[],\"modTurbo\":false,\"fuelLevel\":65.0,\"modVanityPlate\":-1,\"engineHealth\":1000.0,\"modRoof\":-1,\"wheels\":1,\"modLivery\":-1,\"modRearBumper\":-1,\"modAPlate\":-1,\"modSteeringWheel\":-1,\"plateIndex\":0,\"modFender\":-1,\"modTrunk\":-1,\"modSeats\":-1,\"modEngineBlock\":-1,\"modSmokeEnabled\":false,\"modFrontBumper\":-1,\"plate\":\"GSO 367\",\"modTransmission\":-1,\"modStruts\":-1,\"xenonColor\":255,\"neonEnabled\":[false,false,false,false],\"model\":-2122646867,\"modArchCover\":-1}', 'car', 'civ', NULL, 'Unknown', 100, 1, NULL, NULL, 'legion', 'legion'),
('662689f1c506ddac941a41b5604e40d3209a5507', 'JAA 434', '{\"modAPlate\":-1,\"modVanityPlate\":-1,\"modRightFender\":-1,\"modRoof\":-1,\"wheels\":1,\"modHorns\":-1,\"xenonColor\":255,\"modEngine\":-1,\"modTank\":-1,\"modStruts\":-1,\"modShifterLeavers\":-1,\"engineHealth\":1000.0,\"modWindows\":-1,\"pearlescentColor\":7,\"modSideSkirt\":-1,\"modExhaust\":-1,\"modEngineBlock\":-1,\"windowTint\":-1,\"modAirFilter\":-1,\"modDashboard\":-1,\"modArchCover\":-1,\"dirtLevel\":7.0,\"modTrunk\":-1,\"tankHealth\":1000.0,\"wheelColor\":156,\"modPlateHolder\":-1,\"modFrontWheels\":-1,\"modFrontBumper\":-1,\"bodyHealth\":1000.0,\"modOrnaments\":-1,\"modSmokeEnabled\":false,\"modHydrolic\":-1,\"modXenon\":false,\"modSuspension\":-1,\"modBackWheels\":-1,\"modAerials\":-1,\"plate\":\"JAA 434\",\"extras\":{\"11\":false,\"10\":true,\"4\":false},\"modSeats\":-1,\"modBrakes\":-1,\"modDoorSpeaker\":-1,\"color2\":11,\"modTurbo\":false,\"neonEnabled\":[false,false,false,false],\"modArmor\":-1,\"modTransmission\":-1,\"modLivery\":-1,\"neonColor\":[255,0,255],\"modFrame\":-1,\"plateIndex\":2,\"color1\":11,\"modSpoilers\":-1,\"modFender\":-1,\"modGrille\":-1,\"modHood\":-1,\"modTrimB\":-1,\"fuelLevel\":65.0,\"tyreSmokeColor\":[255,255,255],\"modRearBumper\":-1,\"modDial\":-1,\"modTrimA\":-1,\"modSpeakers\":-1,\"modSteeringWheel\":-1,\"model\":-2095439403}', 'car', 'civ', NULL, 'Unknown', 100, 1, NULL, NULL, 'legion', 'legion'),
('662689f1c506ddac941a41b5604e40d3209a5507', 'OEH 133', '{\"modAPlate\":-1,\"modVanityPlate\":-1,\"modRightFender\":-1,\"modRoof\":-1,\"wheels\":1,\"modHorns\":-1,\"xenonColor\":255,\"modEngine\":-1,\"modTank\":-1,\"modStruts\":-1,\"modShifterLeavers\":-1,\"engineHealth\":1000.0,\"modWindows\":-1,\"pearlescentColor\":7,\"modSideSkirt\":-1,\"modExhaust\":-1,\"modEngineBlock\":-1,\"windowTint\":-1,\"modAirFilter\":-1,\"modDashboard\":-1,\"modArchCover\":-1,\"dirtLevel\":1.0,\"modTrunk\":-1,\"tankHealth\":1000.0,\"wheelColor\":0,\"modPlateHolder\":-1,\"modFrontWheels\":-1,\"modFrontBumper\":-1,\"bodyHealth\":1000.0,\"modOrnaments\":-1,\"modSmokeEnabled\":false,\"modHydrolic\":-1,\"modXenon\":false,\"modSuspension\":-1,\"modBackWheels\":-1,\"modAerials\":-1,\"plate\":\"OEH 133\",\"extras\":[],\"modSeats\":-1,\"modBrakes\":-1,\"modDoorSpeaker\":-1,\"color2\":120,\"modTurbo\":false,\"neonEnabled\":[false,false,false,false],\"modArmor\":-1,\"modTransmission\":-1,\"modLivery\":-1,\"neonColor\":[255,0,255],\"modFrame\":-1,\"plateIndex\":0,\"color1\":0,\"modSpoilers\":-1,\"modFender\":-1,\"modGrille\":-1,\"modHood\":-1,\"modTrimB\":-1,\"fuelLevel\":65.0,\"tyreSmokeColor\":[255,255,255],\"modRearBumper\":-1,\"modDial\":-1,\"modTrimA\":-1,\"modSpeakers\":-1,\"modSteeringWheel\":-1,\"model\":1009171724}', 'car', 'civ', NULL, 'Unknown', 100, 1, NULL, NULL, 'legion', 'legion'),
('662689f1c506ddac941a41b5604e40d3209a5507', 'SUA 267', '{\"modExhaust\":-1,\"modEngine\":-1,\"bodyHealth\":1000.0,\"modFender\":-1,\"wheels\":1,\"modStruts\":-1,\"modFrame\":-1,\"wheelColor\":156,\"modShifterLeavers\":-1,\"modSideSkirt\":-1,\"modDoorSpeaker\":-1,\"plateIndex\":0,\"engineHealth\":1000.0,\"modSpeakers\":-1,\"neonColor\":[255,0,255],\"modVanityPlate\":-1,\"modArmor\":-1,\"modTurbo\":false,\"modSeats\":-1,\"modGrille\":-1,\"modPlateHolder\":-1,\"modTrimA\":-1,\"modSteeringWheel\":-1,\"fuelLevel\":65.0,\"modAirFilter\":-1,\"modBackWheels\":-1,\"modLivery\":-1,\"extras\":[],\"modRearBumper\":-1,\"modTrunk\":-1,\"xenonColor\":255,\"pearlescentColor\":134,\"modSmokeEnabled\":false,\"modAerials\":-1,\"modSuspension\":-1,\"windowTint\":-1,\"modArchCover\":-1,\"tankHealth\":1000.0,\"modTank\":-1,\"modEngineBlock\":-1,\"modBrakes\":-1,\"modSpoilers\":-1,\"modAPlate\":-1,\"neonEnabled\":[false,false,false,false],\"modXenon\":false,\"tyreSmokeColor\":[255,255,255],\"modDashboard\":-1,\"modRightFender\":-1,\"modDial\":-1,\"modTrimB\":-1,\"color2\":4,\"modHood\":-1,\"modFrontBumper\":-1,\"modFrontWheels\":-1,\"model\":-882629065,\"plate\":\"SUA 267\",\"dirtLevel\":1.0,\"modHorns\":-1,\"color1\":4,\"modOrnaments\":-1,\"modHydrolic\":-1,\"modTransmission\":-1,\"modWindows\":-1,\"modRoof\":-1}', 'car', 'civ', NULL, 'Unknown', 100, 1, NULL, NULL, 'legion', 'legion'),
('662689f1c506ddac941a41b5604e40d3209a5507', 'VQW 488', '{\"modFender\":-1,\"modRearBumper\":-1,\"bodyHealth\":999,\"modWindows\":-1,\"modExhaust\":-1,\"modBackWheels\":-1,\"modHood\":-1,\"modEngineBlock\":-1,\"modTank\":-1,\"modVanityPlate\":-1,\"modLightbar\":-1,\"modAPlate\":-1,\"modHydraulics\":false,\"modDashboard\":-1,\"modArchCover\":-1,\"tankHealth\":1000,\"modTurbo\":false,\"modSpoilers\":-1,\"wheelColor\":0,\"modDial\":-1,\"modHydrolic\":-1,\"modTrimA\":-1,\"modAirFilter\":-1,\"modFrontWheels\":-1,\"model\":941494461,\"windowTint\":-1,\"engineHealth\":984,\"modRoof\":-1,\"modSideSkirt\":-1,\"fuelLevel\":77,\"wheels\":1,\"modGrille\":-1,\"modSuspension\":-1,\"neonColor\":[255,0,255],\"modSeats\":-1,\"modSubwoofer\":-1,\"modSmokeEnabled\":false,\"modFrame\":-1,\"modCustomTiresF\":false,\"modTrunk\":-1,\"modSteeringWheel\":-1,\"modFrontBumper\":-1,\"pearlescentColor\":18,\"tyreSmokeColor\":[255,255,255],\"modAerials\":-1,\"modXenon\":false,\"color2\":0,\"modHorns\":-1,\"modBrakes\":-1,\"modSpeakers\":-1,\"modEngine\":-1,\"modLivery\":-1,\"modCustomTiresR\":false,\"modTransmission\":-1,\"plateIndex\":0,\"neonEnabled\":[],\"modStruts\":-1,\"modDoorSpeaker\":-1,\"interiorColor\":0,\"modPlateHolder\":-1,\"color1\":0,\"xenonColor\":255,\"extras\":[null,null,null,null,null,null,false],\"modNitrous\":-1,\"modShifterLeavers\":-1,\"dirtLevel\":7,\"modTrimB\":-1,\"modOrnaments\":-1,\"modArmor\":-1,\"plate\":\"VQW 488 \",\"dashboardColor\":0,\"modRightFender\":-1,\"modDoorR\":-1}', 'car', 'civ', NULL, 'Unknown', 100, 1, NULL, '{\"parts\":{\"tires\":[],\"doors\":[],\"windows\":[2,3,4,5,6,7]},\"body\":998.75,\"fuel\":77.29,\"engine\":984.06}', 'legion', 'legion'),
('police', 'YHB  895', '{\"plate\":\"YHB  895\",\"model\":380432924}', 'car', 'police', 'cars', 'Crown Vic', 100, 1, 'https://wiki.rage.mp/images/thumb/b/bf/Police.png/800px-Police.png', NULL, 'legion', NULL),
('ambulance', 'ZHZ  342', '{\"engineHealth\":1000.0,\"modVanityPlate\":-1,\"xenonColor\":255,\"modDial\":-1,\"modTrimB\":-1,\"modTransmission\":-1,\"wheelColor\":156,\"bodyHealth\":1000.0,\"color1\":112,\"neonColor\":[255,0,255],\"modTank\":-1,\"pearlescentColor\":112,\"modDashboard\":-1,\"modTrimA\":-1,\"modTrunk\":-1,\"modGrille\":-1,\"modEngineBlock\":-1,\"modStruts\":-1,\"modAerials\":-1,\"modBrakes\":-1,\"modAPlate\":-1,\"modWindows\":-1,\"modSpoilers\":-1,\"modHorns\":-1,\"modSmokeEnabled\":false,\"modFrontBumper\":-1,\"dirtLevel\":0.0,\"modArchCover\":-1,\"plate\":\"ZHZ  342\",\"extras\":{\"6\":true,\"5\":true,\"4\":true,\"3\":true,\"2\":true,\"1\":true,\"12\":true,\"11\":true,\"10\":true,\"9\":true,\"8\":true,\"7\":true},\"modExhaust\":-1,\"modPlateHolder\":-1,\"modRearBumper\":-1,\"modLivery\":0,\"modHydrolic\":-1,\"tyreSmokeColor\":[255,255,255],\"modHood\":-1,\"wheels\":0,\"modSteeringWheel\":-1,\"modSideSkirt\":-1,\"modRoof\":-1,\"modXenon\":false,\"modFrontWheels\":-1,\"plateIndex\":4,\"modRightFender\":-1,\"modBackWheels\":-1,\"modDoorSpeaker\":-1,\"modShifterLeavers\":-1,\"modFender\":-1,\"neonEnabled\":[false,false,false,false],\"fuelLevel\":69.9,\"modTurbo\":false,\"modArmor\":-1,\"windowTint\":-1,\"modSeats\":-1,\"modFrame\":-1,\"tankHealth\":1000.0,\"modSuspension\":-1,\"modAirFilter\":-1,\"modSpeakers\":-1,\"modEngine\":-1,\"color2\":28,\"modOrnaments\":-1,\"model\":1171614426}', 'car', 'ambulance', 'cars', 'Ambulance', 70, 1, 'https://wiki.rage.mp/images/thumb/f/f5/Ambulance.png/800px-Ambulance.png', NULL, 'legion', NULL);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `owned_vehicles`
--
ALTER TABLE `owned_vehicles`
  ADD PRIMARY KEY (`plate`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by frazz1234** [comment]
like that --- https://we.tl/t-2Tspxhkvcu

**Comment by LukeWasTakenn** [comment]
Hmm,
Can you add this line:
```lua
print(v,plate, Locale('garage'), GetGarageLabel(v.garage))
```
Above the table.insert on this line:
https://github.com/LukeWasTakenn/luke_garages/blob/a2216c2d4367da1667a3061f1fcc3d0916b76302/client/client.lua#L319

**Comment by frazz1234** [comment]
![20220329200851_1](https://user-images.githubusercontent.com/66176776/160725947-26b60199-a253-44ba-8480-bd86f182e5b6.jpg)

**Comment by LukeWasTakenn** [comment]
Huh interesting, your plate is a table and the locale for garage is nil.

What locale do you use?

**Comment by frazz1234** [comment]
French

**Comment by frazz1234** [comment]
Anyidea body?

**Comment by frazz1234** [comment]
Im gonna be frankly whit you, i redownload the realese, and everything is good. but i can confirm i was on the last one before that too.. any i think its fix

**Comment by LukeWasTakenn** [comment]
Yeah I had no other people report the issue and I couldn't reproduce it myself so it must've been something weird.
