### ISSUE TITLE
Boat stored error

### ISSUE THREAD

**Issue by ItzTrivial** [LukeWasTakenn/luke_garages#79]
I have a problem with the vehicletype 'boat'

If I buy a boat and just take it out of the garage once, without storing it again the database is correct and shows garage as "none" and stored as "0". If I restart the server after that and refresh the database stored somehow resets to "1" for every single boat. This is only happening with the type "boat".

Cars and aircrafts are still shown as stored "0" in the exact same scenario.

Problem: Because of the boats "stored" state being 1 an the garage being "none" the script is basically not working when opening the boat-garage, since it cant read the vehicles properly.

I hope you are able to recreate that problem.
Thanks up front, Trivial

**Comment by LukeWasTakenn** [comment]
Tested, could not reproduce.
