### ISSUE TITLE
Feature request - Job specific garages

### ISSUE THREAD

**Issue by duckysuck** [LukeWasTakenn/luke_garages#82]
Add functionality for job specific garages. Ambulance, Police, Mechanics.
The ped for ambulance for instance would be outside of the hospital, the ped for police would be outside of the police station etc.

I'm happy to help test, tweak or even give some of this a go myself with a helping hand.

**Comment by LukeWasTakenn** [comment]
Already a feature.

https://github.com/LukeWasTakenn/luke_garages/blob/8d337c8f7d8099af783276f94a65869f4d2c3abd/config.lua#L198-L249
