### ISSUE TITLE
several same vehicles are not displayed

### ISSUE THREAD

**Issue by janwichmann12** [LukeWasTakenn/luke_garages#90]
I have 3x the same vehicle only with different license plates but only one of them is listed

**Comment by LukeWasTakenn** [comment]
Can reproduce, this is likely happening because the names of the vehicles are the same and I'm passing them as keys, which you can't have duplicates of.

Will be fixed.

**Comment by LukeWasTakenn** [comment]
Resolved in commit fe4b857e7df4ab3281506e8054039c41933f8898
