### ISSUE TITLE
Garage issues

### ISSUE THREAD

**Issue by Tinky124** [LukeWasTakenn/luke_garages#91]
People can put helicopter in car garage, but i cant take out from that garage

**Comment by LukeWasTakenn** [comment]
I'll test it out when I get around to it

**Comment by Tinky124** [comment]
@LukeWasTakenn Did you tested?

**Comment by LukeWasTakenn** [comment]
> @LukeWasTakenn Did you tested?

Yep, happens with all the vehicle types, not just aircrafts.

**Comment by xMaKii** [comment]
sorry for joining in ticket, but i got same problem on garages (2021. version) and i downloaded a new version, but same.... of 64 player on my server, 15-20 got problem with taking out vehicle from a garage

**Comment by LukeWasTakenn** [comment]
> sorry for joining in ticket, but i got same problem on garages (2021. version) and i downloaded a new version, but same.... of 64 player on my server, 15-20 got problem with taking out vehicle from a garage

Is this in relevance to the current this issue or is this something else?

**Comment by LukeWasTakenn** [comment]
Resolved in commit d24a9d82ceda57e374e12d30595bf29c1308a7b5
