### ISSUE TITLE
Split garage issue

### ISSUE THREAD

**Issue by inahokaizuki** [LukeWasTakenn/luke_garages#92]
config.splitgarage doesnt work.. 
everybody can take their vehicle from any garage ... 
, but in the menu name they saved as the same garage lates you saved it

**Comment by LukeWasTakenn** [comment]
> but in the menu name they saved as the same garage lates you saved it

what?

**Comment by inahokaizuki** [comment]
everybody can take their vehicle from any garage... 
even in your menu status is from another one garage
example :

i store it into legion 
then ill go to my other civ garage ..
i still can spawn the car in your status "legion"
even im in the "other" garage

**Comment by KrisnaCahya** [comment]
Yep, I'm having the same problem too

**Comment by LukeWasTakenn** [comment]
Resolved in 162fb37c54d4733edf92b350654383d3e4dea78f.
