### ISSUE TITLE
Broken Vehicles can get fixed once you put it inside the garage

### ISSUE THREAD

**Issue by Elyyyy1412** [LukeWasTakenn/luke_garages#97]
Broken Vehicles can get fixed once you put it inside the garage and put it outside. Please fix it

**Comment by LukeWasTakenn** [comment]
Vehicles get repaired to their bare minimum driving state if they are damaged enough, this also, isn't controlled by my resource but rather by ox_lib which is applying the vehicle properties onto the vehicle.
