### ISSUE TITLE
Data issues

### ISSUE THREAD

**Issue by Rota911** [LukeWasTakenn/luke_garages#98]
Hello! i use 2.6.2 version of the garage. i downloaded the latest nh-context menu and rewrote txt (in a newer version called context)
and deleted params since it is no more. I restart the script and i got error and i dont know why. Image of the error
![image](https://user-images.githubusercontent.com/88843688/173243044-51813ca5-8cfa-4e52-aead-8e3b601bc70a.png)
![image](https://user-images.githubusercontent.com/88843688/173243057-206e0bcb-79d4-4bc9-8bf5-a2ef99401199.png)

**Comment by LukeWasTakenn** [comment]
Older versions of the resource are unsupported and are considered deprecated.
